export const PROGRAMING_LANGUAGES = {
    TypeScript: "/typescript.svg",
    JavaScript: "/javascript.svg",
    Python: "/python.svg",
    C: "/c.svg",
    Cpp: "/cpp.svg",
    Java: "/java.svg",
    CSharp: "/csharp.svg",
    HTML: "/html.svg",
    CSS: "/css.svg",
    PHP: "/php.svg",
    Ruby: "/ruby.svg",
    Swift: "/swift.svg",
    Kotlin: "/kotlin.svg",
    Go: "/go.svg",
    Dart: "/dart.svg",
    Haskell: "/haskell.svg",
    Rust: "/rust.svg",
    Scala: "/scala.svg",
    SQL: "/sql.svg",
}